{
 "title": "Hyperledger Stats",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "peer", "label": "Peer", "query": "label_values(instance)" },
   { "name": "orderer", "label": "Orderer", "query": "label_values(instance)" },
   { "name": "chaincode", "label": "Chaincode", "query": "label_values(chaincode)" },
   { "name": "logLevel", "label": "Log Level", "query": "label_values(level)" }
  ]
 },
 "panels": [
  { "title": "Basic Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ledger Blockchain Height",
   "type": "bargauge",
   "description": "Ledger Blockchain Height",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(ledger_blockchain_height{channel=\"mychannel\"})"
    }
   ]
  },
  {
   "title": "Number of Raft Nodes in This Channel",
   "type": "singlestat",
   "description": "Number of raft nodes in this channel",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(consensus_etcdraft_cluster_size{channel=\"mychannel\"})"
    }
   ]
  },
  {
   "title": "Number of Raft Leader Changes Since Process Start",
   "type": "singlestat",
   "description": "The number of raft leader changes since process start",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(consensus_etcdraft_leader_changes{channel=\"mychannel\"})"
    }
   ]
  },
  {
   "title": "The Leadership Status of Raft Nodes",
   "type": "table",
   "description": "The leadership status of the current raft node: 1 if it is the leader else 0",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "consensus_etcdraft_is_leader{channel=\"mychannel\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gossip Leader Status (Among Peers)",
   "type": "table",
   "description": "Peer is gossip leader (1) or follower (0)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "gossip_leader_election_leader{channel=\"mychannel\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Known Peers Via Gossip Protocol",
   "type": "table",
   "description": "Total known peers via gossip protocol",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "gossip_membership_total_peers_known{channel=\"mychannel\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Requests Made to Enroll API",
   "type": "bargauge",
   "description": "Number of requests made to enroll API.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "api_request_count{api_name=\"enroll\",status_code=\"201\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Requests Made to Register API",
   "type": "bargauge",
   "description": "Number of requests made to register API",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "api_request_count{api_name=\"register\",status_code=\"201\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Number of Written Log Entries",
   "type": "graph",
   "description": "Number of log entries that are written",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logging_entries_written{level=~\"$logLevel\",instance=~\"$peer|$orderer\"}",
     "legendFormat": "{{instance}} - {{level}}"
    }
   ]
  },
  {
   "title": "Number of Gossip Messages Received",
   "type": "graph",
   "description": "Number of gossip messages received",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gossip_comm_messages_received{instance=~\"$peer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Gossip Messages Sent",
   "type": "graph",
   "description": "Number of gossip messages sent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gossip_comm_messages_sent{instance=~\"$peer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blockchain Related Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ledger Blockchain Height",
     "type": "graph",
     "description": "Ledger Blockchain Height",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ledger_blockchain_height{channel=\"mychannel\",instance=~\"$peer|$orderer\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of Transactions Processed",
     "type": "graph",
     "description": "Number of transactions processed",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ledger_transaction_count{chaincode=~\"$chaincode\",channel=\"mychannel\",transaction_type=~\"ENDORSER_TRANSACTION|CONFIG\",validation_code=\"VALID\",instance=~\"$peer|$orderer\"}",
       "legendFormat": "{{instance}} - {{transaction_type}} - {{chaincode}}"
      }
     ]
    },
    {
     "title": "Number of Proposals",
     "type": "graph",
     "description": "The number of proposals received/was successful/that have failed initial validation.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "endorser_proposals_received{instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - received"
      },
      {
       "expr": "endorser_successful_proposals{instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - successful"
      },
      {
       "expr": "endorser_proposal_validation_failures{instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - faild"
      }
     ]
    }
   ]
  },
  {
   "title": "Chaincode Related Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Chaincode Shim Requests (GET_STATE)",
     "type": "graph",
     "description": "The number of chaincode shim requests completed/received\nof type GET_STATE.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "chaincode_shim_requests_completed{chaincode=~\"$chaincode\",channel=\"mychannel\",success=\"true\",type=\"GET_STATE\",instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - {{chaincode}} - completed"
      },
      {
       "expr": "chaincode_shim_requests_received{chaincode=~\"$chaincode\",channel=\"mychannel\",type=\"GET_STATE\",instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - {{chaincode}} - received"
      }
     ]
    },
    {
     "title": "Cumulated Time to Complete Chaincode Shim Requests (GET_STATE)",
     "type": "graph",
     "description": "Cumulated time to complete chaincode shim requests\nof type GET_STATE.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "chaincode_shim_request_duration_sum{chaincode=~\"$chaincode\",channel=\"mychannel\",success=\"true\",type=\"GET_STATE\",instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - {{chaincode}}"
      }
     ]
    },
    {
     "title": "Number of Chaincode Shim Requests (PUT_STATE)",
     "type": "graph",
     "description": "The number of chaincode shim requests completed/received\nof type PUT_STATE.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "chaincode_shim_requests_completed{chaincode=~\"$chaincode\",channel=\"mychannel\",success=\"true\",type=\"PUT_STATE\",instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - {{chaincode}} - completed"
      },
      {
       "expr": "chaincode_shim_requests_received{chaincode=~\"$chaincode\",channel=\"mychannel\",type=\"PUT_STATE\",instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - {{chaincode}} - received"
      }
     ]
    },
    {
     "title": "Cumulated Time to Complete Chaincode Shim Requests (PUT_STATE)",
     "type": "graph",
     "description": "Cumulated time to complete chaincode shim requests\nof type PUT_STATE.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "chaincode_shim_request_duration_sum{chaincode=~\"$chaincode\",channel=\"mychannel\",success=\"true\",type=\"PUT_STATE\",instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - {{chaincode}}"
      }
     ]
    },
    {
     "title": "Number of Chaincode Shim Requests",
     "type": "graph",
     "description": "The number of chaincode shim requests completed/received\nof type GET_STATE_BY_RANGE/GET_QUARY_RESULT/QUARY_STATE_CLOSE.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "chaincode_shim_requests_completed{chaincode=~\"$chaincode\",channel=\"mychannel\",success=\"true\",type=\"GET_STATE_BY_RANGE\",instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - {{chaincode}} -{{type}} - completed"
      },
      {
       "expr": "chaincode_shim_requests_received{chaincode=~\"$chaincode\",channel=\"mychannel\",type=\"GET_STATE_BY_RANGE\",instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - {{chaincode}} -{{type}} - received"
      },
      {
       "expr": "chaincode_shim_requests_completed{chaincode=~\"$chaincode\",channel=\"mychannel\",success=\"true\",type=\"GET_QUERY_RESULT\",instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - {{chaincode}} -{{type}} -  completed"
      },
      {
       "expr": "chaincode_shim_requests_received{chaincode=~\"$chaincode\",channel=\"mychannel\",type=\"GET_QUERY_RESULT\",instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - {{chaincode}} -{{type}} -  received"
      },
      {
       "expr": "chaincode_shim_requests_completed{chaincode=~\"$chaincode\",channel=\"mychannel\",success=\"true\",type=\"QUERY_STATE_CLOSE\",instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - {{chaincode}} - {{type}} -  completed"
      },
      {
       "expr": "chaincode_shim_requests_received{chaincode=~\"$chaincode\",channel=\"mychannel\",type=\"QUERY_STATE_CLOSE\",instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - {{chaincode}} - {{type}} - received"
      }
     ]
    },
    {
     "title": "Cumulated Time to Complete Chaincode Shim Requests",
     "type": "graph",
     "description": "Cumulated time to complete chaincode shim requests\nof type GET_STATE_BY_RANGE/GET_QUARY_RESULT/QUARY_STATE_CLOSE.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "chaincode_shim_request_duration_sum{chaincode=~\"$chaincode\",channel=\"mychannel\",success=\"true\",type=\"GET_STATE_BY_RANGE\",instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - {{chaincode}} -{{type}}"
      },
      {
       "expr": "chaincode_shim_request_duration_sum{chaincode=~\"$chaincode\",channel=\"mychannel\",success=\"true\",type=\"GET_QUERY_RESULT\",instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - {{chaincode}} -{{type}}"
      },
      {
       "expr": "chaincode_shim_request_duration_sum{chaincode=~\"$chaincode\",channel=\"mychannel\",success=\"true\",type=\"QUERY_STATE_CLOSE\",instance=~\"$peer\"}",
       "legendFormat": "{{instance}} - {{chaincode}} - {{type}}"
      }
     ]
    },
    {
     "title": "Time to Build a Chaincode Image (seconds)",
     "type": "graph",
     "description": "The time to build a chaincode image in seconds",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dockercontroller_chaincode_container_build_duration_sum{success=\"true\"}",
       "legendFormat": "{{instance}} - {{chaincode}}"
      }
     ]
    },
    {
     "title": "Time to Launch a Chaincode (seconds)",
     "type": "graph",
     "description": "The time to launch a chaincode",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "chaincode_launch_duration_sum{success=\"true\",instance=~\"$peer\",chaincode=~\"$chaincode\"}",
       "legendFormat": "{{instance}} - {{chaincode}}"
      }
     ]
    }
   ]
  }
 ]
}