
# SPDX-License-Identifier: Apache-2.0
version: '2'

# volumes:
  # pgdata:
  # walletstore:

networks:
  mynetwork.com:
    external:
      name: artifacts_default

services:

  explorerdb.mynetwork.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.mynetwork.com
    hostname: explorerdb.mynetwork.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    volumes:
      - ./Monitoring-Config/blockchain-explorer/config/createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
      #- pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork.com
    logging:
      options:
        max-size: 50m  

  explorer.mynetwork.com:
    image: hyperledger/explorer:latest
    container_name: explorer.mynetwork.com
    hostname: explorer.mynetwork.com
    environment:
      - DATABASE_HOST=explorerdb.mynetwork.com
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./Monitoring-Config/blockchain-explorer/profile/scm/config.json:/opt/explorer/app/platform/fabric/config.json
      - ./Monitoring-Config/blockchain-explorer/profile/scm/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./Monitoring-Config/blockchain-explorer/profile/scm/crypto:/tmp/crypto
      #- walletstore:/opt/wallet
    command: sh -c "sleep 16&& node /opt/explorer/main.js && tail -f /dev/null"
    ports:
      - 8090:8080
    networks:
      - mynetwork.com
    logging:
      options:
        max-size: 50m  
